use_frameworks!

target 'KeyboardSpy_Example' do
  pod 'KeyboardSpy', :path => '../'
  pod 'SnapKit'
  pod 'Material'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'Material'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.2'
            end
        end
    end
end
